spring.datasource.url=jdbc:postgresql://dpg-d7nu291j2pic73crb6vg-a.oregon-postgres.render.com:5432/elearning_db_embc
spring.datasource.username=elearning_db_embc_user
spring.datasource.password=rivFWaY7HcQfSpZz8Fl5GjV8JoWUnmGj
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB